CREATE TABLE IF NOT EXISTS Account
(
    id         SERIAL PRIMARY KEY,
    nickname  VARCHAR(255) UNIQUE NOT NULL,
    user_name  VARCHAR(255) UNIQUE NOT NULL,
    password  VARCHAR(255) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);