export const SignInResultCode = {
  SUCCESS: 0,
  INVALID_ID: 1,
  INVALID_PW: 2,
  ALREADY_LOGGED_IN: 3,
};

export const SignUpResultCode = {
  SUCCESS: 0,
  ID_INVALID: 1,
  PW_INVALID: 2,
  NN_INVALID: 3,
  DUPLICATE_USER_NAME: 5,
  DUPLICATE_NICKNAME: 6,
  FAILED_CREATE: Number.MAX_SAFE_INTEGER - 1,
  UNKNOWN_ERROR: Number.MAX_SAFE_INTEGER,
};
