export const PACKET_TYPE_LENGTH = 2; // 패킷타입을 나타내는  길이
export const PACKET_VERSION_LENGTH = 1; //버전 문자열 길이
export const PACKET_SEQUENCE_LENGTH = 4; //시퀀스 데이터 길이
export const PACKET_PAYLOAD_LENGTH = 4; //페이로드 데이터 길이

export const PacketType = {
  // 게임 상태 관련 데이터
  GAME_STATE: 1,
  ITEM_DATA: 2,
  PLAYER_ROOM_INFO: 3,
  PLAYER_INITIAL_DATA: 4,
  PLAYER_STATE: 5,
  FIELD_UNIT: 6,
  POSITION: 7,
  BASE_DATA: 8,
  TOWER_DATA: 9,
  MONSTER_DATA: 10,

  // 회원가입 및 로그인
  SIGN_UP_REQUEST: 11,
  SIGN_UP_RESPONSE: 12,
  SIGN_IN_REQUEST: 13,
  SIGN_IN_RESPONSE: 14,

  // 토큰 재발급
  REFRESH_TOKEN_REQUEST: 15,
  REFRESH_TOKEN_RESPONSE: 16,

  // 대기실 관련 요청 및 응답
  CREATE_ROOM_REQUEST: 17,
  CREATE_ROOM_RESPONSE: 18,
  MATCH_CANCEL_REQUEST: 19,
  MATCH_PROGRESS_NOTIFICATION: 20,

  // 대기실 입장 및 나가기
  JOIN_ROOM_REQUEST: 21,
  JOIN_ROOM_RESPONSE: 22,
  QUIT_ROOM_REQUEST: 23,
  QUIT_ROOM_NOTIFICATION: 24,

  // 팀 변경
  TEAM_CHANGE_REQUEST: 25,
  TEAM_CHANGE_NOTIFICATION: 26,

  // 대기실 동기화 및 게임 시작
  SYNC_ROOM_NOTIFICATION: 27,
  GAME_START_REQUEST: 28,
  GAME_START_RESPONSE: 29,

  // 로딩 진행
  LOAD_PROGRESS_NOTIFICATION: 30,
  SYNC_LOAD_NOTIFICATION: 31,

  // 초기 정보 동기화
  INITIAL_NOTIFICATION: 32,

  // 플레이어 및 상태 동기화
  SYNC_PLAYERS_NOTIFICATION: 33,
  SYNC_FURNACE_STATE_NOTIFICATION: 34,
  SAWMILL_STATUS_NOTIFICATION: 35,
  WORKBENCH_STATUS_NOTIFICATION: 36,

  // 플레이어 액션
  PLAYER_ACTION_REQUEST: 37,
  PLAYER_ACTION_RESPONSE: 38,

  // 객체 관련
  SPAWN_OBJECT_NOTIFICATION: 39,
  DESTROY_OBJECT_REQUEST: 40,
  DESTROY_OBJECT_NOTIFICATION: 41,

  // 전장 유닛 동기화
  SYNC_FIELD_UNIT_NOTIFICATION: 42,

  // 항복
  SURRENDER_REQUEST: 43,
  SURRENDER_RESPONSE: 44,
  SURRENDER_NOTIFICATION: 45,

  // 게임 종료
  GAME_OVER_NOTIFICATION: 46,

  // 공용맵 이동
  MOVE_TO_AREA_MAP_REQUEST: 47,
  MOVE_TO_AREA_MAP_RESPONSE: 48,

  // 조합대
  WORKBENCH_REQUEST: 49,
  WORKBENCH_RESPONSE: 50,

  // 용광로
  FURNACE_REQUEST: 51,
  FURNACE_RESPONSE: 52,

  // 제제소
  SAWMILL_REQUEST: 53,
  SAWMILL_RESPONSE: 54,

  // 헬스체크
  PING_REQUEST: 55,
  PONG_RESPONSE: 56,
};

export const ReversePacketType = Object.fromEntries(
  Object.entries(PacketType).map(([key, value]) => [value, key]),
);
